apiVersion: apps/v1
kind: Deployment
metadata:
  name: iron-gallery-deployment-xfusion
  labels:
    run: iron-gallery
  namespace: iron-namespace-xfusion
spec:
  replicas: 1
  selector:
    matchLabels:
      run: iron-gallery
  template:
    metadata:
      labels:
        run: iron-gallery
    spec:
      containers:
      - name: iron-gallery-container-xfusion
        image: kodekloud/irongallery:2.0
        resources:
          limits:
            memory: "100Mi"
            cpu: "50m"
        volumeMounts:
        - name: config
          mountPath: /usr/share/nginx/html/data
        - name: images
          mountPath: /usr/share/nginx/html/uploads
        ports:
        - containerPort: 80
      volumes:
      - name: config
        emptyDir: {}
      - name: images
        emptyDir: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iron-db-deployment-xfusion
  labels:
    db: mariadb
  namespace: iron-namespace-xfusion
spec:
  replicas: 1
  selector:
    matchLabels:
      db: mariadb
  template:
    metadata:
      labels:
        db: mariadb
    spec:
      containers:
      - name: iron-db-container-xfusion
        image: kodekloud/irondb:2.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "irongallery"
        - name: MYSQL_DATABASE
          value: "database_blog"
        - name: MYSQL_USER
          value: "irongallery"
        - name: MYSQL_PASSWORD
          value: "irongallery"
        volumeMounts:
        - name: db
          mountPath: /var/lib/mysql
        ports:
        - containerPort: 3306
      volumes:
      - name: db
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: iron-db-service-xfusion
  namespace: iron-namespace-xfusion
  labels:
    db: mariadb
spec:
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    db: mariadb
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: iron-gallery-service-xfusion
  namespace: iron-namespace-xfusion
  labels:
    run: iron-gallery
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 32678
  selector:
    run: iron-gallery
  type: NodePort
