apiVersion: v1
kind: Pod
metadata:
  name: secret-devops
  labels:
    app: devops
spec:
  containers:
  - name: secret-container-devops
    image: debian:latest
    command: ["/bin/sh", "-c", "while true; do sleep 5; done"]
    volumeMounts:
    - name: secret-volume
      mountPath: /opt/cluster
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi
  volumes:
  - name: secret-volume
    secret:
      secretName: media
    