apiVersion: apps/v1
kind: Deployment
metadata:
  name: ic-deploy-devops
  labels:
    app: ic-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ic-devops
  template:
    metadata:
      labels:
        app: ic-devops
    spec:
      initContainers:
      - name: ic-msg-devops
        image: debian:latest
        command: ["/bin/bash", "-c", "echo 'Init Done - Welcome to xFusionCorp Industries' > /ic/media"]
        volumeMounts:
        - name: ic-volume-devops
          mountPath: /ic
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
      containers:
      - name: ic-main-devops
        image: debian:latest
        command: ["/bin/bash", "-c", 'while true; do cat /ic/media; sleep 5; done']
        volumeMounts:
        - name: ic-volume-devops
          mountPath: /ic
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
      volumes:
        - name: ic-volume-devops
          emptyDir: {}
